from flask import Blueprint, jsonify
from utils.predictor import simulate_attack
from utils.mapper import ATTACK_MAPPING
from utils.severity import get_severity
from utils.db import get_db
from utils.ip_generator import random_ip
import psutil
import time
import os
import subprocess

# =====================================================================
# 🌟 NEW ADDITIONS FOR FCM NOTIFICATION SUPPORT
# =====================================================================
import firebase_admin
from firebase_admin import credentials, messaging

# Initialize Firebase Admin SDK using your service account private key file.
# Make sure your 'serviceAccountKey.json' file is downloaded from the 
# Firebase Console and placed right next to your main application run file!
try:
    cred = credentials.Certificate("serviceAccountKey.json")
    firebase_admin.initialize_app(cred)
    print("Firebase Admin SDK successfully initialized.")
except Exception as e:
    print(f"Warning: Firebase initialization skipped or failed: {e}")

def send_fcm_notification(alert_id, attack_type, severity):
    """
    Broadcasts a push notification payload out to Google's Firebase servers.
    Any Android device subscribed to the 'alerts' topic cluster will receive it.
    """
    try:
        message = messaging.Message(
            # Visible alert banner details displayed in the system tray
            notification=messaging.Notification(
                title=f"🚨 Critical Threat Detected: {attack_type}",
                body=f"Severity: {severity}. Tap to inspect full network metrics immediately."
            ),
            # Key-value data block processed by Android's NidsMessagingService
            data={
                "click_action": "FLUTTER_NOTIFICATION_CLICK",
                "deep_link_uri": f"nidsapp://alert/{alert_id}" # Read by Jetpack Compose NavHost
            },
            topic="alerts" # Broadcast target channel
        )
        # Relay the payload construction to Firebase Cloud Messaging api
        response = messaging.send(message)
        print(f"FCM notification dispatched successfully: {response}")
    except Exception as e:
        print(f"Failed to transmit message to FCM: {e}")
# =====================================================================

api_bp = Blueprint("api", __name__)

# SIMULATE ATTACK
@api_bp.route("/api/simulate/<int:class_id>")
def simulate(class_id):
    result = simulate_attack(class_id)
    prediction_id = result["prediction"]
    attack_name = ATTACK_MAPPING[prediction_id]
    severity = get_severity(attack_name)
    src_ip = random_ip()
    dst_ip = random_ip()
    
    conn = get_db()
    
    # Execute the alert transaction record mapping
    cursor = conn.execute("""
    INSERT INTO alerts(
        attack_type,
        prediction,
        severity,
        src_ip,
        dst_ip,
        source_port,
        destination_port,
        protocol,
        flow_duration
    )
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        attack_name,
        prediction_id,
        severity,
        src_ip,
        dst_ip,
        result["source_port"],
        result["destination_port"],
        result["protocol"],
        result["flow_duration"]
    ))
    
    # =====================================================================
    # 🌟 NEW ADDITION: CAPTURE LAST ROW ID FOR THE DEEP LINK
    # =====================================================================
    # We must grab the exact autoincrement ID generated by SQLite for this row 
    # so we can push it within our URI string down to the phone.
    generated_id = cursor.lastrowid
    # =====================================================================
    
    conn.commit()
    conn.close()
    
    # =====================================================================
    # 🌟 NEW ADDITION: TRANSMIT POPUP ALERTS ON TRAFFIC SIMULATION
    # =====================================================================
    # Trigger the notification delivery block right after confirming the DB entry.
    # We wrap it to pass the fresh generated database index token smoothly.
    send_fcm_notification(generated_id, attack_name, severity)
    # =====================================================================

    return jsonify({
        "attack": attack_name,
        "severity": severity,
        "src_ip": src_ip,
        "dst_ip": dst_ip
    })


# GET ALERTS
@api_bp.route("/api/alerts")
def get_alerts():
    conn = get_db()
    alerts = conn.execute("""
    SELECT * FROM alerts
    ORDER BY timestamp DESC
    """).fetchall()
    conn.close()
    return jsonify([dict(row) for row in alerts])


# GET SINGLE ALERT
@api_bp.route("/api/alerts/<int:id>")
def get_alert(id):
    conn = get_db()
    alert = conn.execute("""
    SELECT * FROM alerts
    WHERE id=?
    """, (id,)).fetchone()
    conn.close()
    
    if alert is None:
        return jsonify({"error": "Not found"}), 404
        
    return jsonify(dict(alert))


# STATS
@api_bp.route("/api/stats")
def stats():
    conn = get_db()
    total = conn.execute("""
    SELECT COUNT(*) as count FROM alerts
    """).fetchone()["count"]
    high = conn.execute("""
    SELECT COUNT(*) as count
    FROM alerts
    WHERE severity='High'
    """).fetchone()["count"]
    medium = conn.execute("""
    SELECT COUNT(*) as count
    FROM alerts
    WHERE severity='Medium'
    """).fetchone()["count"]
    low = conn.execute("""
    SELECT COUNT(*) as count
    FROM alerts
    WHERE severity='Low'
    """).fetchone()["count"]
    conn.close()
    return jsonify({
        "total_alerts": total,
        "high_alerts": high,
        "medium_alerts": medium,
        "low_alerts": low
    })


# HEALTH
prev_packets_recv = psutil.net_io_counters().packets_recv
prev_packets_sent = psutil.net_io_counters().packets_sent
prev_time = time.time()

@api_bp.route("/api/health", methods=['GET'])
def health():
    global prev_packets_recv, prev_packets_sent, prev_time
    
    current_time = time.time()
    elapsed_time = current_time - prev_time if (current_time - prev_time) > 0 else 1
    io_counters = psutil.net_io_counters()
    
    # Calculate Rates
    pps_received = round((io_counters.packets_recv - prev_packets_recv) / elapsed_time, 1)
    pps_sent = round((io_counters.packets_sent - prev_packets_sent) / elapsed_time, 1)
    
    prev_packets_recv = io_counters.packets_recv
    prev_packets_sent = io_counters.packets_sent
    prev_time = current_time

    # Latency Check
    try:
        param = '-n' if os.name == 'nt' else '-c'
        command = ['ping', param, '1', '127.0.0.1']
        start_ping = time.time()
        output = subprocess.run(command, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=1)
        latency = f"{round((time.time() - start_ping) * 1000, 1)} ms" if output.returncode == 0 else "TIMEOUT"
    except Exception:
        latency = "ERR"

    # Socket Inspection
    try:
        connections = psutil.net_connections(kind='inet')
        states = {"ESTABLISHED": 0, "SYN_RECV": 0, "TIME_WAIT": 0, "SYN_SENT": 0}
        for conn in connections:
            if conn.status in states:
                states[conn.status] += 1
    except Exception:
        states = {"ESTABLISHED": 0, "SYN_RECV": 0, "TIME_WAIT": 0, "SYN_SENT": 0}

    # DB Connection Check
    try:
        conn = get_db()
        conn.execute("SELECT 1")
        conn.close()
        db_status = "connected"
    except Exception:
        db_status = "error"

    # Return the structured payload matching your advanced monitor
    return jsonify({
        "cpu_percent": psutil.cpu_percent(interval=0.1),
        "memory_percent": psutil.virtual_memory().percent,
        "disk_percent": psutil.disk_usage('/').percent,
        "pps_in": pps_received,
        "pps_out": pps_sent,
        "mb_recv": round(io_counters.bytes_recv / (1024 * 1024), 2),
        "mb_sent": round(io_counters.bytes_sent / (1024 * 1024), 2),
        "latency": latency,
        "errors": io_counters.errin,
        "drops": io_counters.dropin,
        "established": states["ESTABLISHED"],
        "syn_recv": states["SYN_RECV"],
        "time_wait": states["TIME_WAIT"],
        "syn_sent": states["SYN_SENT"],
        "db_status": db_status
    })


# RESOLVE ALERT
@api_bp.route("/api/resolve/<int:id>")
def resolve_alert(id):
    conn = get_db()
    conn.execute("""
    UPDATE alerts
    SET status='RESOLVED'
    WHERE id=?
    """, (id,))
    conn.commit()
    conn.close()
    return jsonify({
        "message": "resolved"
    })


# REAL-TIME FEED — returns recent events, optionally only those after ?since=<id>
from flask import request as flask_request

@api_bp.route("/api/realtime")
def realtime_feed():
    since_id = flask_request.args.get("since", type=int, default=0)
    limit = flask_request.args.get("limit", type=int, default=20)

    conn = get_db()

    if since_id > 0:
        # Incremental mode: only return new alerts after the given ID
        rows = conn.execute("""
        SELECT id, timestamp, src_ip, dst_ip, attack_type, severity, status
        FROM alerts
        WHERE id > ?
        ORDER BY id DESC
        LIMIT ?
        """, (since_id, limit)).fetchall()
    else:
        # Initial load: return last N events
        rows = conn.execute("""
        SELECT id, timestamp, src_ip, dst_ip, attack_type, severity, status
        FROM alerts
        ORDER BY id DESC
        LIMIT ?
        """, (limit,)).fetchall()

    conn.close()
    return jsonify([dict(row) for row in rows])